{{- with .Values.wellKnownDelegation -}}
{{- if .enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "matrix-stack.well-known.labels" (dict "context" . "root" $) | nindent 4 }}
  {{- with .labels -}}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-well-known-delegation
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "matrix-stack.well-known.selector-labels" (dict "context" . "root" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matrix-stack.well-known.labels" (dict "context" . "root" $) | nindent 8 }}
      {{- with .labels -}}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/well-known/configmap.yaml") $ | sha256sum }}
      {{- with .annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with (concat .image.pullSecrets $.Values.image.pullSecrets) | uniq }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: nginx
          {{- include "matrix-stack.common.image" (dict "context" .image "root" $) | indent 10 }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
            httpGet:
              path: /health
              port: health
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
            httpGet:
              path: /health
              port: health
          startupProbe:
            {{- toYaml .startupProbe | nindent 12 }}
            httpGet:
              path: /health
              port: health
          {{- with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: well-known
              mountPath: /usr/share/nginx/html/.well-known/matrix
            - name: nginx
              mountPath: /etc/nginx/conf.d
            - name: tmp
              mountPath: /tmp
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: well-known
          configMap:
            name: {{ include "matrix-stack.fullname" $ }}-well-known-delegation
        - name: nginx
          configMap:
            name: {{ include "matrix-stack.fullname" $ }}-well-known-delegation-nginx
        - name: tmp
          emptyDir:
            medium: Memory
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
