{{- with .Values.wellKnownDelegation -}}
{{- if .enabled -}}
{{- with .httpRoute -}}
{{- if .enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  labels:
    {{- include "matrix-stack.well-known.labels" (dict "context" $.Values.wellKnownDelegation "root" $) | nindent 4 }}
  {{- with deepCopy $.Values.wellKnownDelegation.annotations | merge .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-well-known-delegation
  namespace: {{ $.Release.Namespace }}
spec:
  {{- with .parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  hostnames:
    - {{ $.Values.serverName }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "matrix-stack.fullname" $ }}-well-known-delegation
          port: 8080
{{- end }}
{{- end }}
{{- end }}
{{- end }}
