{{- if .Values.synapse.enabled -}}
{{- with .Values.matrixAuthenticationService -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "matrix-stack.matrix-authentication-service.labels" (dict "context" . "root" $) | nindent 4 }}
  {{- with .labels -}}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "matrix-stack.matrix-authentication-service.selector-labels" (dict "context" . "root" $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matrix-stack.matrix-authentication-service.labels" (dict "context" . "root" $) | nindent 8 }}
      {{- with .labels -}}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/matrix-authentication-service/configmap.yaml") $ | sha256sum }}
      {{- with .annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with (concat .image.pullSecrets $.Values.image.pullSecrets) | uniq }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: render-config
          {{- include "matrix-stack.common.image" (dict "context" $.Values.matrixTools.image "root" $) | indent 10 }}
          args:
            - render-config
            - -output
            - /config/config.yaml
            - /templates/config.yaml
          {{- with .postgres }}
          env:
            {{- range (include "matrix-stack.matrix-authentication-service.postgres-secrets" (dict "context" . "root" $) | fromYamlArray) -}}
            {{ $secretPath := include "matrix-stack.common.secret-path" (dict
              "context" (dict
                "valuePath" (printf "matrixAuthenticationService.postgres.%s" .property)
                "initSecretKey" (include (printf "matrix-stack.matrix-authentication-service.secret-keys.postgres-%s" .property) .)
              )
              "root" $
            ) }}
            - name: {{ printf "MAS_POSTGRES_%s" .property | upper }}
              value: '{{ printf "{{ readfile \"/secrets/%s\" | quote }}" $secretPath }}'
            {{- end }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-initial
              mountPath: /templates
              readOnly: true
            - name: config-rendered
              mountPath: /config
              readOnly: false
            {{- include "matrix-stack.common.secret-volumemounts" (dict "context" (dict "component" "matrix-authentication-service") "root" $) | indent 12 }}
      containers:
        - name: matrix-authentication-service
          {{- include "matrix-stack.common.image" (dict "context" .image "root" $) | indent 10 }}
          args:
            - server
          env:
            - name: MAS_CONFIG
              value: /config/config.yaml
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: internal
              protocol: TCP
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
            httpGet:
              path: /health
              port: internal
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
            httpGet:
              path: /health
              port: internal
          startupProbe:
            {{- toYaml .startupProbe | nindent 12 }}
            httpGet:
              path: /health
              port: internal
          {{- with .resources }}
          resources:
            {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-rendered
              mountPath: /config
              readOnly: true
            {{- include "matrix-stack.common.secret-volumemounts" (dict "context" (dict "component" "matrix-authentication-service") "root" $) | indent 12 }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-initial
          configMap:
            name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
        - name: config-rendered
          emptyDir:
            medium: Memory
        {{- include "matrix-stack.common.secret-volumes" (dict "context" (dict "component" "matrix-authentication-service") "root" $) | indent 8 }}
        - name: tmp
          emptyDir:
            medium: Memory
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
