{{- if .Values.synapse.enabled -}}
{{- with .Values.matrixAuthenticationService.ingress -}}
{{- if .enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "matrix-stack.matrix-authentication-service.labels" (dict "context" $.Values.matrixAuthenticationService "root" $) | nindent 4 }}
  {{- with deepCopy $.Values.matrixAuthenticationService.annotations | merge .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
spec:
  {{- with .className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    - host: {{ $.Values.matrixAuthenticationService.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
                port:
                  number: 8080
  {{- if .tls }}
  tls:
    - hosts:
        - {{ $.Values.matrixAuthenticationService.host }}
      secretName: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service-tls
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
