{{- if .Values.synapse.enabled -}}
{{- with .Values.matrixAuthenticationService -}}
{{- if include "matrix-stack.matrix-authentication-service.provided-secret-data" (dict "context" . "root") -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "matrix-stack.matrix-authentication-service.labels" (dict "context" . "root" $) | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
data:
  {{- include "matrix-stack.matrix-authentication-service.provided-secret-data" (dict "context" . "root" $) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
