{{- if .Values.synapse.enabled -}}
{{- with .Values.matrixAuthenticationService -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "matrix-stack.matrix-authentication-service.labels" (dict "context" . "root" $) | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-matrix-authentication-service
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "matrix-stack.matrix-authentication-service.selector-labels" (dict "context" . "root" $) | nindent 4 }}
{{- end }}
{{- end }}
