{{- with .Values.initSecrets -}}
{{- if and .enabled .rbac.create (include "matrix-stack.init-secrets.generated-secrets" (dict "context" . "root" $)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
  labels:
    {{- include "matrix-stack.init-secrets.labels" (dict "context" . "root" $) | nindent 4 }}
  name: {{ include "matrix-stack.fullname" $ }}-init-secrets
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    {{- $resourceNames := list -}}
    {{- if $.Values.synapse.enabled -}}
    {{- $resourceNames = append $resourceNames (printf "%s-synapse-generated" (include "matrix-stack.fullname" $)) -}}
    {{- $resourceNames = append $resourceNames (printf "%s-matrix-authentication-service-generated" (include "matrix-stack.fullname" $)) -}}
    {{- end -}}
    {{- with $resourceNames }}
    resourceNames:
    {{- range .}}
      - {{ . }}
    {{- end}}
    {{- end }}
    verbs: ["get", "update"]
{{- end }}
{{- end }}
