{{- with .Values.initSecrets -}}
{{- if and .enabled .rbac.create (include "matrix-stack.init-secrets.generated-secrets" (dict "context" . "root" $)) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
  labels:
    {{- include "matrix-stack.init-secrets.labels" (dict "context" . "root" $) | nindent 4 }}
  name: {{ include "matrix-stack.fullname" $ }}-init-secrets
  namespace: {{ $.Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "matrix-stack.fullname" $ }}-init-secrets
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "matrix-stack.fullname" $ }}-init-secrets
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
