{{- with .Values.synapse -}}
{{- if .enabled -}}
{{- if include "matrix-stack.synapse.provided-secret-data" (dict "context" . "root") -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    {{- include "matrix-stack.synapse.labels" (dict "context" . "root" $) | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "matrix-stack.fullname" $ }}-synapse
  namespace: {{ $.Release.Namespace }}
data:
  {{- include "matrix-stack.synapse.provided-secret-data" (dict "context" . "root" $) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
